#############################################################################
# Makefile for building: 7-qt
# Generated by qmake (2.01a) (Qt 4.8.5) on: Thu Jan 23 16:27:02 2014
# Project:  7-qt.pro
# Template: app
# Command: /home/fred/winqt/bin/qmake -o Makefile 7-qt.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = /home/fred/winqt/bin/qmake
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: 7-qt.pro  ../../winqt/mkspecs/win32-g++/qmake.conf ../../winqt/mkspecs/qdevice.pri \
		../../winqt/mkspecs/features/device_config.prf \
		../../winqt/mkspecs/qconfig.pri \
		../../winqt/mkspecs/features/qt_functions.prf \
		../../winqt/mkspecs/features/qt_config.prf \
		../../winqt/mkspecs/features/exclusive_builds.prf \
		../../winqt/mkspecs/features/default_pre.prf \
		../../winqt/mkspecs/features/win32/default_pre.prf \
		../../winqt/mkspecs/features/debug.prf \
		../../winqt/mkspecs/features/debug_and_release.prf \
		../../winqt/mkspecs/features/default_post.prf \
		../../winqt/mkspecs/features/win32/default_post.prf \
		../../winqt/mkspecs/features/win32/stl.prf \
		../../winqt/mkspecs/features/win32/rtti.prf \
		../../winqt/mkspecs/features/win32/exceptions.prf \
		../../winqt/mkspecs/features/shared.prf \
		../../winqt/mkspecs/features/warn_on.prf \
		../../winqt/mkspecs/features/qt.prf \
		../../winqt/mkspecs/features/win32/thread.prf \
		../../winqt/mkspecs/features/moc.prf \
		../../winqt/mkspecs/features/win32/windows.prf \
		../../winqt/mkspecs/features/resources.prf \
		../../winqt/mkspecs/features/uic.prf \
		../../winqt/mkspecs/features/yacc.prf \
		../../winqt/mkspecs/features/lex.prf \
		/home/fred/winqt/lib/qtmaind.prl
	$(QMAKE) -o Makefile 7-qt.pro
../../winqt/mkspecs/qdevice.pri:
../../winqt/mkspecs/features/device_config.prf:
../../winqt/mkspecs/qconfig.pri:
../../winqt/mkspecs/features/qt_functions.prf:
../../winqt/mkspecs/features/qt_config.prf:
../../winqt/mkspecs/features/exclusive_builds.prf:
../../winqt/mkspecs/features/default_pre.prf:
../../winqt/mkspecs/features/win32/default_pre.prf:
../../winqt/mkspecs/features/debug.prf:
../../winqt/mkspecs/features/debug_and_release.prf:
../../winqt/mkspecs/features/default_post.prf:
../../winqt/mkspecs/features/win32/default_post.prf:
../../winqt/mkspecs/features/win32/stl.prf:
../../winqt/mkspecs/features/win32/rtti.prf:
../../winqt/mkspecs/features/win32/exceptions.prf:
../../winqt/mkspecs/features/shared.prf:
../../winqt/mkspecs/features/warn_on.prf:
../../winqt/mkspecs/features/qt.prf:
../../winqt/mkspecs/features/win32/thread.prf:
../../winqt/mkspecs/features/moc.prf:
../../winqt/mkspecs/features/win32/windows.prf:
../../winqt/mkspecs/features/resources.prf:
../../winqt/mkspecs/features/uic.prf:
../../winqt/mkspecs/features/yacc.prf:
../../winqt/mkspecs/features/lex.prf:
/home/fred/winqt/lib/qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile 7-qt.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
